### PR TITLE
WSAD (can be changed in upLeftDownRightKeys.ini) for moving around and

### PR DESCRIPTION
**Pull request by przwr**
SPACEBAR (while hold Mouse Clicks don't pick stuff just move); Requires actionKeys.ini in settings folder for changing SPACEBAR to something else.

### CODE REVIEW

**Comment by wrobelp** [comment]
@jasonrohrer Can I get any response to this pull request? Did You consider to merge it with master?

**Comment by przwr** [comment]
Jason! Will You put this in game? Can I get any response to that?

**Comment by Jookia** [comment]
I'll try this in my client. I'm not sure if it unbalances the game, but it looks like a good idea since it was something I asked in my head.

**Comment by jasonrohrer** [comment]
Better to leave this as a mod for now.

Not sure what effect this would have on server load if people were micro-managing their moves in a crowded map.

**Comment by RandyStevens** [comment]
Is there any chance that you could tell me how to easily apply this "mod" @wrobelp ?
Is it as simple as making sure my OHOL client is up to date and then merging these changes into my local master branch?

**Comment by przwr** [comment]
Yea. But make sure you have the version that client uses. Not the newest from repository. Then just merge with my repo.

**Pull request closed without merging**
