### PR TITLE
Allow configuration of server paths with environment variables

### PR DESCRIPTION
**Pull request by colinmarc**
This allows configuration of paths for a server with three environment variables:

 - `OHOL_LOG_PATH`: where `log.txt`, `foodLog`, `failureLog`, etc go
 - `OHOL_DB_PATH`: where kissdb files are stored, along with `recentPlacements.txt`, `nextPlayerID.txt`, and `nextSequenceNumber.txt` (see below)
 - `OHOL_SETTINGS_PATH`: where setting files are read from

For my custom server, I'd like to set these to something like `/var/ohol/logs`, `/var/ohol/db`, and `/etc/ohol`, respectively. This would solve a few problems. For one, it would be easier to update without having to stash/unstash server settings (right now if you change the port, and then run `pullAndBuildLatest`, it wipes your settings). Second, it'd remove (most of) the cruft in the server directory, which also interferes with git (this is separately mitigated by #13; I ran `git clean -f` earlier while updating, and nearly wiped my server, which is what prompted these PRs). Finally, it's a step towards the ultimate goal being able to have the binary work without write access to the directory where it lives (for my sanity 😄 ).

As a related change, it also moves `nextPlayerID.ini` and `nextSequenceNumber.ini` to text files in the db path (or the working directory).

### CODE REVIEW

**Comment by jasonrohrer** [comment]
Hmmm... this is a pretty complicated change that touches a lot of files.

You're bypassing the SettingsManager which is used uniformly throughout client and server.

I think it would be better to modify SettingsManager in minorGems.  It already has this:

static void setDirectoryName( const char *inName );

Not sure if it would work with absolute paths.  But you could call that once when the server starts up.

But it looks like you only want certain settings to be in different places?

**Comment by jasonrohrer** [comment]
Also, I'm a little weirded out by the use of the ENV for this...  does that work on every platform?

**Comment by colinmarc** [comment]
> You're bypassing the SettingsManager which is used uniformly throughout client and server.
>
> I think it would be better to modify SettingsManager in minorGems. It already has this:
>
>     static void setDirectoryName( const char *inName );

That's what the PR does, actually :) https://github.com/jasonrohrer/OneLife/pull/15/files#diff-3985278eaa02e0ecb1c184941c13eeb3R3520

> Also, I'm a little weirded out by the use of the ENV for this... does that work on every platform?

What would you rather use? The db/log paths could be set in a normal settings `.ini`, but the settings directory has to be chosen before that. The other option is a command line argument, but that means probably pulling in a dependency. `getenv` is supposedly portable, although I've never written any code for windows and I'd be surprised if people were using windows to host servers.

I know the PR looks long, but it's lots of just replacing `File( NULL, "foo" )` with `File( getEnvPath(), "foo" )`. Also, each of the commits are independent changes, if you want to pick a subset of them.

**Comment by jasonrohrer** [comment]
So you set the settings folder path in one spot, then why do you need:

writeNextSequenceNumber();

And such?

You're still using the SettingsManager to read these settings.  Why not use it to write the settings too?

If you want the reads and writes to come from and go to different places, that's a strange thing to want, because the sequence number is supposed to be preserved across runs to prevent replay attacks.

Looks like you want those to be stored with the DB path.... but then they won't be loaded correctly if you're using the settings path to load them, right?  I may be missing something.


I also think a simpler solution would be some kind of other script that will copy the server and such out to a working directory instead of in the git repo.  Use git to pull and then build there, but then copy the latest binary out...

I know this doesn't solve your writable binary problem, nor does it give you a bunch of separate paths.  But it would at least solve the git settings overwriting problem.


And finally, I imagine that when the server is eventually released, the vast majority of people who try to run it will be on Windows trying to run it to play solo or whatever.  I pretty much avoid anything other than generic file reading/writing for settings and data.  No ENV, no registry, no command line args (at least not for end-user software.... I imagine that someday, the primary way people will start the server will be double-clicking on a .BAT file).

**Comment by colinmarc** [comment]
>If you want the reads and writes to come from and go to different places, that's a strange thing to want, because the sequence number is supposed to be preserved across runs to prevent replay attacks.
>
> Looks like you want those to be stored with the DB path.... but then they won't be loaded correctly if you're using the settings path to load them, right? I may be missing something.

The PR doesn't just write to `nextSequenceNumber.txt`, it also reads from that. So it changes it from a setting to a state file, like the DB files.

What was the motivation for making it a setting at all? Do users often need to munge the next sequence number or player ID? I think it's kinda odd to have the binary changing server settings on you...

Making it not a setting is a distinct change, but I bundled it together in this PR since the goal is the same: having a read-only settings dir that isn't in the same place as the binary.

> I also think a simpler solution would be some kind of other script that will copy the server and such out to a working directory instead of in the git repo. Use git to pull and then build there, but then copy the latest binary out...

The git repo isn't the only problem. I'd like to be able to run the server as non-root, for security reasons. If the binary needs to be able to write to the directory where it's installed, then you can't run it as non-root and have it installed in a root-owned place (like` /usr/local`).

> And finally, I imagine that when the server is eventually released, the vast majority of people who try to run it will be on Windows trying to run it to play solo or whatever. I pretty much avoid anything other than generic file reading/writing for settings and data. No ENV, no registry, no command line args (at least not for end-user software.... I imagine that someday, the primary way people will start the server will be double-clicking on a .BAT file).

Something I was careful to preserve with this change is that the configuration isn't required. If you don't set the ENV variables, the server dumps everything into the working directory, like before.

**Comment by colinmarc** [comment]
If you look at https://github.com/jasonrohrer/OneLife/pull/15/commits/34380818931adf4fdaee8142edfab378324d1d8a, it contains just the changes related to `nextSequenceNumber.txt` and `nextPlayerID.txt`.

**Comment by jasonrohrer** [comment]
Wow... you're right.  I don't know what I was seeing when I looked at it last time.  Hmm...

I see what you're saying about these things not actually being settings....  but I guess that's just the way I've always done it, mostly to leverage the SettingsManager's setting and getting stuff.

I don't run my servers as root.

And what's the security gained by installing the server in a write-only location?

I mean, if your system is compromised, the attacker will have access to a compiler, right?

Or are you worried about the EXE file being overwritten through some other channel?

Do you have a good security article that I can read about this issue?

**Comment by colinmarc** [comment]
Sorry, I said that in reverse. I already run the server as an `ohol` user, and have everything inside a `chown`'d directory in `/opt`. This works ok and I feel reasonably secure about it (it should probably actually be in `/home/ohol`, the more I think about it).

The problems come about if you want to install the binary in a standard way, to, say `/usr/local`. There are benefits to this but they aren't really security-related (it means you don't have to worry about accidentally breaking the server, etc). But obviously you don't want anything in `/usr/local` to be writable, especially if it's on your `$PATH`.

So I'm not really saying there are security issues with it being able to drop stuff at its feet, but for those of us that like to have our servers neat and organized there are security issues preventing us from doing that.

The other issue, which I should be driving more at, is that without being able to configure a separate settings directory, you have to do gymnastics not to lose your settings when you build a new version. The easiest way right now is to copy your settings out, and then copy them back in after you update.

You effectively sidestep this problem by checking your settings into git. :) But it would be better if the settings in git were the actual defaults, not the ones running on the public servers.

P.S. Thanks for engaging on this with me! I've got a couple other ideas for making running a custom server more painless, so I'm glad you're open to discussion/PRs for that.

**Comment by jasonrohrer** [comment]
Well, I just found a name for the way I'm doing things... DevOps...

It's all about the rapid and automated deployment of changes directly to the end users.

I'm using git to do most of that lifting, including deploying settings changes to all 15 of my game servers.

And some of those settings are NOT set to defaults, but as long as the update doesn't touch them, they are left in place.

Is it the "checkout" part of the script that is overwriting your local changes?

For example, if you change the port, as long as I don't change the default port, it shouldn't overwrite your local change, right?

It should leave your "M settings/severPort.ini" in place, even when checking out a tag, right?

But yeah, I do keep tweaking maxPlayers, so that would cause it to complain if your setting was different.

**Comment by colinmarc** [comment]
Right - if you tweak a setting and I have it changed, the script breaks: `error: Your local changes to the following files would be overwritten by checkout...`

So currently I `git stash` and then `git stash pop` after. It works but I usually have to fiddle around a bit.

(The script has never built the server for me, by the way. It only seems to build the client.)

**Comment by ghost** [comment]
@jasonrohrer I realize this PR is a bit old but...

Have you considered containerizing the server package using docker? This will be beneficial for both your official servers and custom servers for users. You can setup the docker image however you want and just create documentation for the mount points users will need to use for configuration and persistent data. Containers will behave consistently across platforms and users dont need to fiddle with vm creation, dependencies, and shell scripts. Nowadays even Windows has good native support for Docker via Hyper-V.

The whole flow can easily be setup using something like Travis, a privately deployed Gitlab-ce or whatever else CI/CD tool you might choose to use, and the resulting image can be pushed to docker hub, for both users and your servers to pull.

For your own official servers, you can further automate and simply your CI/CD pipeline by leveraging container orchestration like Kubernetes or Docker Swarm. This has been the new hot thing in DevOps since about 2015.

**Comment by jasonrohrer** [comment]
What is docker?

I really don't have time to investigate a whole new way of doing things at this point.

**Comment by ghost** [comment]
@jasonrohrer 

Docker is a container engine using Linux cgroups https://en.wikipedia.org/wiki/Cgroups.

Basically its an image with a bare minimum operating system, application dependencies, binaries, configuration, and whatever else you need to run your application. It differs from a virtual machine in that you cannot run the container on its own, it must be run inside of a bare metal or virtual machine that has the Docker engine installed. On non-*nix platforms, when you install the Docker engine it actually creates a transparent virtual machine to run containers, as a user you dont need to care about it.

Docker fulfills the same needs as the Java virtual machine and that is a platform-agnostic and ready-to-use package. It differs from the JVM in that you can use any language and put any binaries in your container, without the need to use a specific language like Java.

When something like this is setup, users should be able to run their servers in the exact same way as your production servers (since the docker image is identical), the only difference is the configuration and data being persisted.

You actually have an example of the server setup by another user on your forums, but I think he/she didnt finish the data mount. https://github.com/theraccoonbear/OHOL

**Comment by FlorianLudwig** [comment]
> You actually have an example of the server setup by another user on your forums, but I think he/she didnt finish the data mount. https://github.com/theraccoonbear/OHOL

I actually made it work via symlinks for all mutable files.  I moved them into two sub directories: `db` and `settings`. 

You can start a ohol server after installing docker with one line like this (for an old v77 server ;)):

```
docker run -p 8005:8005 -v `pwd`/db/:/opt/OneLife/server/db/ -v `pwd`/settings:/opt/OneLife/server/settings/ ludwigf/ohol-server:77-77-76
```
This expects the folders `db` and `settings` in your current working directory.

It will download the compressed image (4mb) and start the server. No compilation needed. And should work on any linux system no matter what your setup.

**Pull request closed without merging**
